module.exports={
	cookieSecret:'wyyGensokyo',
	account:{
		user:'gensoukyo',
		password:'VTSI5duLTD0AtKzE'
	},
	mongo:{
		dev:{
			connectionstring:'mongodb+srv://gensoukyo:VTSI5duLTD0AtKzE@cluster-3zl8s.mongodb.net/test'
		}
	}
};